# Generated by Django 3.1.6 on 2021-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='answer',
            field=models.CharField(default='NA', max_length=120),
        ),
        migrations.AlterField(
            model_name='level',
            name='question',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
