# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_level_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 15, 50, 2, 111189, tzinfo=utc)),
        ),
    ]
