# Generated by Django 3.0.8 on 2021-01-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180114_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
