# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
