# Generated by Django 2.2.5 on 2022-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
