#!/bin/bash

rm -f /etc/nginx/conf.d/default.conf

# Update server name in config file
sed "s/{{SSL_DOMAIN}}/\"$SSL_DOMAIN\"/" nginx.conf > nginx.conf.tmp
mv -f nginx.conf.tmp nginx.conf
echo "SETUP : Updated server name"

cp nginx.conf /etc/nginx/conf.d/
echo "SETUP : Saved NGINX config"


while ! /etc/init.d/nginx restart; do
    echo 'SETUP : restarting nginx...'
    sleep 1
done

while true; do
    /etc/init.d/nginx reload
    sleep 40000
done
