#!/bin/bash

rm -f /etc/nginx/conf.d/default.conf

# Update server name in config file
sed "s/\${SSL_DOMAIN}/\"$SSL_DOMAIN\"/" nginx.conf > nginx.conf
echo "SETUP : Updated server name"

cp nginx.conf /etc/nginx/conf.d/
echo "SETUP : Saved NGINX config"


while ! /etc/init.d/nginx restart; do
    echo 'SETUP : restarting nginx...'
    sleep 1
done

certbot -n --nginx -d "$SSL_DOMAIN" -m "teamiste@gmail.com" --agree-tos --redirect
while true; do
    # Reload nginx to load new config by certbot
    /etc/init.d/nginx reload
    sleep 40000
    certbot renew -n --nginx -d "$SSL_DOMAIN" -m "teamiste@gmail.com" --agree-tos --redirect
done
